name: Frontend CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: 13.219.99.78
        username: jesse
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "build/"
        target: "/home/jesse/frontend"

    - name: Restart web server (optional)
      uses: appleboy/ssh-action@master
      with:
        host: 13.219.99.78
        username: jesse
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo systemctl restart nginx
